version: '2.3'
services:
  nginx:
    depends_on:
      - website
    image: nginx:1.18
    volumes:
      - "./nginx_config/my_site:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: unless-stopped
  website:
    image: registry.insight-centre.org/annsou/projects_website:latest
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    #    volumes:
    #      - "./:/app"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: unless-stopped
